site_name: Yaw VR Documentation
repo_url: https://github.com/Yaw-VR/yaw-documentation
repo_name: Yaw-VR/yaw-documentation
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/git-alt
  features:
    - content.action.edit
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - toc:
      permalink: "#"
plugins:
  - git-committers:
      repository: Yaw-VR/yaw-documentation
      branch: main
      enabled: True
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://yawvr.com
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/YawVR
    - icon: fontawesome/brands/discord
      link: https://discord.gg/pymFJxPRN4
nav:
  - Home: index.md
  - Hardware:
    - Yaw 3:
      - Yaw 3 Assembly: hardware/yaw3/assembly.md
      - Balancing the Simulator: hardware/yaw3/balance.md
      - Connect to Network: hardware/yaw3/connect.md
      - USB Peripherals: hardware/yaw3/peripherals.md
  - Software:
    - Yaw VR Config: software/yawvrconfig.md
    - Infuse VR: software/infusevr.md
    - Game Link: software/gamelink.md
    - VirtualHere: software/virtualhere.md
    - Yaw VR Emulator: software/yawvremu.md